### ISSUE TITLE
`go generate ./...` fails

### ISSUE THREAD

**Issue by breml** [flowchartsman/aql#2]
During my tests for https://github.com/mna/pigeon/pull/123 I tried to re-generate the peg parser and observed, that running `go generate ./...` fails with the following error:

```shell
$ go generate ./...
open aql.peg: no such file or directory
parser/parser.go:3: running "pigeon": exit status 2
```

Looks like a left over when the grammar was moved to the internal package.

**Comment by breml** [comment]
Additionally I found, that it looks like the parser definition has changed for the error `unterminated string, check for missing closing ["] or unescaped [\]`, which is not yet reflected in the tests.

**Comment by flowchartsman** [comment]
Aha, thanks for filing this. I'll take a look and address.

**Comment by flowchartsman** [comment]
I've addressed the issues you raised on the [issue_2](https://github.com/flowchartsman/aql/tree/issue_2) branch in case you want to do any further post-merge verification for mna/pigeon#123. I would have gotten to this sooner, but I was recently added to a very chatty repo that has eaten up my notifications for the past couple of weeks, and I missed it. If you have no further concerns, I'll merge the branch later this week.

**Comment by breml** [comment]
I have no post-merge tests planned. When I did the tests, I just spotted this issues and did the "extra boy scouting" and left an issue for you. Just go ahead with the merging of you PR.
